### ISSUE TITLE
private: active and empty password

### ISSUE THREAD

**Issue by nanart59** [franck-paul/private#2]
Bonjour,

Sauf erreur de ma part, **si aucun mdp n'est entré** et **si le plug est activé**, la protection (blog/mdp) se met en place (page accès restreint) mais l'accès avec return/mdp vide ne semble pas possible...
_note: le message "aucun mdp n'est défini" s'affiche bien dans l'admin du plug._

Pas encore regardé en détail, mais des solutions pour contrer ce pb me semblent applicables, par ex:
* si mdp vide, active est refusé (pas pris en compte)
* champ mdp(s) du formulaire obligatoire

Après réflexion, le pb des champs obligatoires est que le plug refusera d'enregistrer les modifs même si activer n'est pas coché.
_C'est le cas avec l'email dans le plug contact.me, par ex: pas possible de supprimer/laisser vide car obligatoire._
D'où, plutôt penser à une verif du type
- if active and mdp and emel -> activer
- if !active and (!mdp) -> simplement enregistrer (ou conserver?) setting mdp ?
à savoir :
-> active(false), 
-> mdp(empty? ou conservé ?),

De toute façons, pour l'instant, le mdp est a (re-)saisir si on active/réactive le plug

**Comment by franck-paul** [comment]
Merci pour le signalement, je regarderai ça dès que j'aurais une machine à nouveau fonctionnelle…

**Comment by nanart59** [comment]
En fait, c'est un poil plus "différent" de ce que j'ai expliqué.
Ce qu'il faudrait vérifier c'est si le setting "**private->blog_private_pwd**" est vide.
Dans ce cas-là on exige un mdp.

Sinon,  --_vérifié en supprimant le cookie_, si le mdp existe dans le setting, ça ne devrait pas poser de pb, si on tape le bon mdp.

En résumé :
- si le setting n'est pas vide, on peut désactiver le plug et le réactiver
            -- _le mdp étant conservé + on peut aussi le changer dans l'admin du plug_
- si le setting est vide, il faut exiger un mdp (**non vide**) pour l'activer

**Comment by franck-paul** [comment]
Je vais me limiter à empêcher l'activation (sur la page de réglage) si aucun mot de passe n'est renseigné/enregistré. Ça devrait suffire.
