### ISSUE TITLE
Syntax error in Prepend.php

### ISSUE THREAD

**Issue by PatrickMassot** [franck-paul/private#6]
In version 3.5 running on PHP 7.4,  installing this plugin crashes the whole website with the following error in apache logs:
```
PHP Parse error:  syntax error, unexpected 'private' (T_PRIVATE), expecting identifier (T_STRING) in /var/www/blog/plugins/private/src/Prepend.php on line 15
```

I guess PHP is confused by `private` being both a language keyword and part of the namespace used since 17896f92c4d786859902e2de79e5ec4efe5d9704. I don't have PHP8 here but I guess it works with PHP8?

**Comment by franck-paul** [comment]
Yes, PHP 7.4 does not support using private keyword in a namespace.

**Comment by franck-paul** [comment]
You can install the 2.1.1 if you cannot upgrade PHP to 8.0 or upgrade PHP to 8.0 or better to 8.1
